// generated by "sampctl package generate"

#include "hold-action.inc"

#include <test-boilerplate>

main() {
	// write tests for libraries here and run "sampctl package run"
}

public OnPlayerKeyStateChange(playerid, newkeys, oldkeys) {
	if(newkeys & 16 && !(oldkeys & 16)) {
		StartHoldAction(playerid, 10000);
	} else if(!(newkeys & 16) && oldkeys & 16) {
		StopHoldAction(playerid);
	}
}

public OnHoldActionUpdate(playerid, progress) {
	new str[128];
	format(str, sizeof str, "Progress: %d", progress);
	SendClientMessage(playerid, -1, str);
}

public OnHoldActionFinish(playerid) {
	SendClientMessage(playerid, 0xFFFF00FF, "Finished!");
}
